### PR TITLE
Python rewrite is fairly finished

### PR DESCRIPTION
**Pull request by htgoebel**
Please pull the Python rewrite I've been working on.

Code-coverage is approx. 95% (being degraded by some irrelevant code), and tested for Python 2.5, 2.6 and 2.7 on Linux (using tox).

This includes a developers readme so others can start developing easily.

### CODE REVIEW

**Comment by stigkj** [comment]
Too bad it is not possible in GitHub to specify the target branch to merge into. Much better to get this merged into the Python feature branch.

**Comment by baby-gnu** [comment]
Is there chance that the "production-ready state" branche be named something like "prod" instead of master which is not that meanful?

Because my config looks like the following:

```
gitflow.branch.master=prod
gitflow.branch.develop=master
```

The default configuration became:

```
gitflow.branch.prod=master
gitflow.branch.develop=develop
```

Regards.

**Comment by htgoebel** [comment]
@baby-gnu This pull-request is a _re-implementation_ in python, without semantic changes. Please put you change request into a issue by it's own.

**Comment by htgoebel** [comment]
@nvie: It does not look as if you'd merge this pull-request. Why?

**Pull request closed without merging**
