### PR TITLE
Installer for msysgit environment

### PR DESCRIPTION
**Pull request by dolmen**
This patch :
- provides an installer for the msysgit environment
- updates README to use `getopt.exe` from the GnuWin32 binaries of linux-util (issue #73)
- updates README to use the installer

### CODE REVIEW

**Comment by marcoscoelho** [comment]
thanks.. it works, was very easy!

**Comment by jmacdonagh** [comment]
On a clean install, I still needed to copy `cyggcc_s-1.dll`, `cygiconv-2.dll`, `cygintl-8.dll`, and `cygwin1.dll` to Git's `bin` directory (or somewhere else in my `PATH`). `getopt.exe` has them as dependencies. It's possible your environment has them in your `PATH` somewhere. After copying them to Git's `bin` directory git flow worked great.

**Comment by dolmen** [comment]
@jmacdonagh

You did not follow my instructions: use getopt.exe from GnuWin32 instead of the one from cygwin.
Those instructions are both in the README patch, and in the text of this pull request.

**Comment by jmacdonagh** [comment]
@dolmen

Oops, I read the diff and stopped when I saw `linux-util` I assumed Cygwin.

I removed all the Cygwin files and installed the "Complete package" from the link you provided. If you only copy `getopt.exe` from the bin directory it'll complain that `libintl3.dll` can't be found. You have to copy that as well, unless I missed something? The GnuWin32 installer didn't change my `PATH`.

**Comment by nvie** [comment]
Honestly, I cannot really judge the quality of this script. For one thing, I'm not a Windows user and I cannot tell if this is a standardised way of installing scripts in Windows. It seems to me that this is really a single-point solution that automates the ugly steps involved in gathering precompiled DLLs from some other open source projects and tying them all together.

This might work in your situation, but it also means the script needs to be supported. The script is really dependent on the Windows/MSysGit version, the versions of the open source projects where the DLLs reside, and the git-flow version (in case git-flow files change), which makes me a bit hesitant.

All in all, I feel there _is_ a use for this script, but I'm not to keen on including it in the git-flow project itself. How would you feel about creating a separate git-flow MSysGit installer GitHub project, which can be maintained separately from the git-flow itself (just like https://github.com/bobthecow/git-flow-completion)? I could then easily link to it in the Windows installer section of the README.

Let me know what you think.

**Comment by dolmen** [comment]
@nvie
- The script does not deal with the getopt.exe part. However my patch updates the documentation to provide a simpler way to install it. So your comment about DLL versions is not relevant.
- The script only does the gitflow scripts install part : copy them into where msysgit expects them. It can be used both for gitflow initial installation and for upgrades.
- The script does not relies on a particular version of Windows/MSYSGit : it fails cleanly if it can't do its jobs and has many checks for that. Also, it doesn't use at all the msysgit installation : it is written using the native scripting language of Windows. 
- I'm ready to support this script for a long time or to provide a better solution later. I'm a Git user on both Windows and Linux.
- The script is in the contrib directory. Isn't it enough to mark that you don't maintain it yourself?

Please note that this installer is an important part of the user experience for Windows users: they can rely on distribution packagers like in the Linux world.

**Comment by marcoscoelho** [comment]
@nvie

what he said is true!

**Comment by nvie** [comment]
OK, I'll trust you guys on this one ;)

**Pull request merged**
