### PR TITLE
release "backmerge" flag; backwards-compatible and git describe friendly

### PR DESCRIPTION
**Pull request by putermancer**
Vincent,

This is a patch I threw together for use within my organization. The idea is to provide the facility for merging a release tag back into the development branch, for git describe -- I know from your inline comments as well as some list discussions, etc. that you are aware of this and plan to support it in the python rewrite.

This feature was added as an option during release finish, and is false by default to avoid affecting the way anything works by default.

I would love to see support for this in the pre-python git-flow. If these changes make sense to you, great. If not, I can always maintain my own fork until the python version is ready :)

Groetjes,
- Ben

### CODE REVIEW

**Comment by nvie** [comment]
Hi Ben,

I'm sorry for the late reply, but I definitely think this should make it into git-flow (and the original branching model). Although I think this is important, the earliest I can make some time for describing this will be in 2011. I'd like this to be fairly well communicated, in both the README file and in an accompanying article on my blog. My intention is definitely to make the Python rewrite have this behaviour, but your patch to the current (shell script) version is also a very welcome one.

Also, I think this should be the default behaviour for finishes. Support for the "old-style" behaviour should be dropped completely as it adds nothing, really. For now, I'll keep this pull request open until we've at least documented the changed behaviour somewhere.

Thanks,
Vincent

**Comment by sirlancelot** [comment]
This would close #126 as well. I would love to see this incorporated!

**Comment by gvangool** [comment]
As per @nvie, I've added a commit that makes it the default behaviour: 569edee1ea48e8cdd918ecff4caa4e9328ffd9ff

**Comment by putermancer** [comment]
Managing the commits in here got out of hand because when I opened the pull request (first ever) I based it on my fork's `develop` branch, instead of a feature branch, and I decided to update my local fork with some additional pull requests.

Please reference pull request #179 for this issue instead.

**Pull request closed without merging**
