### PR TITLE
Fix typo in git-flow-feature

### PR DESCRIPTION
**Pull request by bloomonkey**
'it pull' -> 'git pull' at line 510

### CODE REVIEW

**Comment by bloomonkey** [comment]
Any chance someone can merge this? 3 duplicates to date: #214 #219 and #220

**Comment by petervanderdoes** [comment]
I fixed it in my fork, with other fixes and enhancements as well: https://github.com/petervanderdoes/gitflow

The last commit here was 4 months ago.

**Comment by bloomonkey** [comment]
Thanks. Trouble with this is that newcomers will tend to always fork the original repository, as there's no mechanism for determining which of the many forks is the most actively maintained, and hence the best to contribute back to :(

Any chance that you could update [your changelog](https://github.com/petervanderdoes/gitflow/blob/develop/Changes.mdown) to credit all those that spotted and submitted fixes for the bug (authors of #212 #214 #219)? Thx

**Comment by petervanderdoes** [comment]
Sure not a problem I'll add them all.

You are correct that new comers always will fork the original repo. I'm trying to pull fixes posted here into my fork and mentioning that I fixed in my fork as well, so that when people do check the issues they know where to go to.

**Comment by bloomonkey** [comment]
Great. Thanks again.

**Pull request closed without merging**
