### PR TITLE
Add debian/ubuntu packaging

### PR DESCRIPTION
**Pull request by kiall**
I've added debian/ubuntu packaging scripts.

Updating the package for new releases is as simple as adding a new section to debian/changelog

Building the packages is simply `dpkg-buildpackage` if you have a gpg key setup, else `dpkg-buildpackage -us -uc` for unsigned packages..

### CODE REVIEW

**Comment by superbobry** [comment]
Just in case you're interested, I already have a working `git-flow` package in my [PPA](https://launchpad.net/~superbobry/+archive/git-stuff). Not sure this stuff should be in the main repo though.

**Comment by kiall** [comment]
@superbobry - ah I didn't find your PPA before doing these :)

Personally I prefer to see packaging with the main project - it means everyone A) knows it exists .. and B) hacks on it :)

**Comment by nvie** [comment]
@kiall: Thanks for the patch! I merged it, but moved your files under contrib.

**Comment by nvie** [comment]
@superbobry: Feel free to submit patches to @kiall's work if you think they offer some extras. This way everybody can work "on the open" at the installer scripts.

It must be noted that I have 0.0% experience with Debian installers, so I'm trusting you guys to provide the community with some good packaging scripts :)

**Comment by superbobry** [comment]
Sure, what do you guys think about making `shflags` an external dependency (a separate package)? `git sumodules` are nice, but not when it comes to packaging :)

**Comment by seanburlington** [comment]
building the package fails with the debian file under contrib - but after moving it back to the root gitflow directory the package  is built and looks good

**Comment by algernon** [comment]
The contrib/debian packaging is... well, lets just say it's very simple. git-flow is packaged and available in Debian squeeze (via backports) and later, with packaging much more useful than the one in contrib/ (for example, it includes bash and zsh completion).

I've prepared #149 to point to the availability in Debian, instead of contrib/debian (which doesn't work out of the box, and lacks certain niceties that the package in Debian proper has).

**Pull request merged**
