### PR TITLE
Added options (-m and -a) on feature finish action that allow to change default merge message.

### PR DESCRIPTION
**Pull request by conf**
Those are:
- custom merge message option (-m)
- custom appended message to a default merge message (-a)
- default addition to -a option via git config option gitflow.feature.finish.append.

Why is this needed?
Some (maybe many) bugtrackers allow closing issues by mentioning them in the commit messages, like `#VM-123 fixed`. That's cool and we like do that. But in our company before closing task the code (a branch) should pass code review. So it would be convenient to automatically add some text into a merge message when branch is merged into mainstream (develop), so task can be closed.

How to test: 
Create test repo with the following: 

```
mkdir /tmp/repo; cd /tmp/repo; git flow init -d; git config gitflow.feature.finish.append '#VM-$(echo $BRANCH | grep -oP "\d+") fixed'; touch README; git add . ; git commit -m "initial commit"
```

As you may noted, config option will be `eval`uated on run, so user basically can use some template logic based on branch-name, that's very convenient.

Test fast-forward merges with following:

```
git flow feature start vm-1234-test; echo commit >> README ; git commit -am 'commit'; git flow feature finish; git log --shortstat -n 1
```

You should see git flow output and something like that in the end:

```
commit 3d9039fb58bf05537ca9de00052d4d20570783a2
Author: Shein Alexey <confik@gmail.com>
Date:   Wed Mar 14 02:55:36 2012 +0500

    commit
    #VM-1234 fixed

 1 files changed, 1 insertions(+), 0 deletions(-)
```

Note #VM-1234 fixed, that was added by my patch.

Test recursive merges with following: 

```
git flow feature start vm-1234-test; echo commit >> README ; git commit -am 'commit'; echo commit >> README ; git commit -am 'commit'; echo commit >> README ; git commit -am 'commit'; git flow feature finish; git log --shortstat  -n 1
```

You should see git flow output and something like that:

```
commit eb527929d89fc1f0b137664c8077f05f5a74dd72
Merge: 3d9039f 319cb16
Author: Shein Alexey <confik@gmail.com>
Date:   Wed Mar 14 02:57:25 2012 +0500

    Merge branch feature/vm-1234-test into develop.
    #VM-1234 fixed

commit 319cb16e5f4a2d4e15c3b8283a4a6c0846760a77
```

You can also specify custom merge message via -m option and append message via -a option if you need some more flexibility.

### CODE REVIEW

**Comment by wprater** [comment]
+1

**Comment by wfscheper** [comment]
I like your implementation of this better than the one I posted in #176. I'm going to close that pull request in favor of this one.

**Comment by conf** [comment]
Thanks! But it seems there's not too much attention here from nvie :(

**Comment by nvie** [comment]
Hi @conf, thanks for your patch. I'm sorry this project did not receive the attention it deserved lately—I've been so involved with a new job, some great projects and getting my business set up. This has put some lag on my open source project's pull request queues unfortunately :(

I've looked at your patch and would love to merge it, but it won't merge cleanly since I've also accepted the patch to add `--squash` support already. Could you have another look at your patch and see how you would implement it in the new situation (ideally without nesting too many if-statements)? These are the relevant lines: https://github.com/mykehsd/gitflow/blob/develop/git-flow-feature#L312-323

I'll close this pull request, then, if you don't mind.

Thanks.

**Comment by conf** [comment]
Hi, Vincent, thank you for the answer. I'll try to update my patch as soon I'll find some time (quite busy for last time too :)).

**Comment by marcvangend** [comment]
I understand that you are busy people, but is there any chance that this will be implemented?

**Comment by conf** [comment]
@marcvangend Hey, thanks for remembering about this patch. Please, try it and say if you have any issues.

**Pull request closed without merging**
