### PR TITLE
minor README change for OSX

### PR DESCRIPTION
**Pull request by defeated**
`wget` doesn't seem to be available by default on OSX, but `curl` is, so I added a line to the README.

### CODE REVIEW

**Comment by zombor** [comment]
I'm actually curious why anyone would pipe an internet URL into a root session like this, and why anyone would recommend it be done. Even if you inspect what you are pulling down first, it just screams all kinds of bad to me.

**Comment by defeated** [comment]
how is the trust level of a shell script downloaded from the internet different from "sudo gem install xxx" (which is also a script downloaded from the internet)?

**Comment by nikreiman** [comment]
Although I agree with the security implications, this addition follows the original style of the readme and should definitely be pulled.  If anyone has a safer mechanism, then that should be committed as a separate patch.

**Comment by nvie** [comment]
I agree with the discussion. It might be a scary thing to do, but defeated's remarks on gem install is equally valid. So yes, because other systems do it unsafe, we're allowing it, too.

I'll pull this one in.

**Pull request closed without merging**
