### PR TITLE
Use https:// instead of git://

### PR DESCRIPTION
**Pull request by fuadsaud**
Makes it easy for people behind a firewall install it via tools like homebrew.

### CODE REVIEW

**Comment by liyanchang** [comment]
Not sure if you noticed #175 It's a bummer that neither fix has been merged in yet.

**Comment by fuadsaud** [comment]
Wow, that's sad :(

The project seems totally abandoned.

**Comment by petervanderdoes** [comment]
Instead of using a submodule I just added the file directly in my fork [git-flow (AVH Edition)](http://bit.ly/S2k1S2). It's been updated from the upstream as well.
My fork has diverged to much to make this into an easy pull request for nvie's gitflow,

Checkout the [changelog](http://bit.ly/YiUfPt) for more information about bugfixes and new features implemented in my fork.

**Comment by fuadsaud** [comment]
Hum, nice. Would you mind providing a Homebrew installation formula? I
don't know if I'll have the time but I can look into it as well.

On Thu, Jun 27, 2013 at 1:00 PM, Peter van der Does <
notifications@github.com> wrote:

> Instead of using a submodule I just added the file directly in my fork git-flow
> (AVH Edition) http://bit.ly/S2k1S2. It's been updated from the upstream
> as well.
> My fork has diverged to much to make this into an easy pull request for
> nvie's gitflow,
> 
> Checkout the changelog http://bit.ly/YiUfPt for more information about
> bugfixes and new features implemented in my fork.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nvie/gitflow/pull/326#issuecomment-20132463
> .

## 

Fuad Saud

twitter http://twitter.com/fuadsaud |
linkedinhttp://www.linkedin.com/in/fuadksd|
coderwall http://coderwal.com/fuadsaud | githubhttp://github.com/fuadsaud|

**Comment by petervanderdoes** [comment]
It's in Homebrew already, it's called git-flow-avh

**Comment by fuadsaud** [comment]
Oh, didn't noticed. Thanks!

**Pull request closed without merging**
