### PR TITLE
Feature and Release squashing options #14

### PR DESCRIPTION
**Pull request by mykehsd**
This allows a -S option to both feature and releasing finishing actions so that users can squash commits into one large one.  Some users like to develop this way an Issue #14 has several up votes for the feature.

### CODE REVIEW

**Comment by mauricio** [comment]
I'd love to see this available.

**Comment by seanhussey** [comment]
+1

Yes, the lack of squashing (and therefore the generated noise) was the #1 impediment to getting colleagues at a former job to adopt git flow.

**Comment by duanefields** [comment]
Chiming in my support, +1

**Comment by arhuman** [comment]
+1

**Pull request merged**
