### PR TITLE
add config option to change the default behavior of git flow feature fin...

### PR DESCRIPTION
**Pull request by salzig**
...ish regarding merge/rebase

This change allows the user to change the default not to rebase to something there wish (project based).

Always rebase feature branches
`git config --global gitflow.feature.rebase true`

Always merge feature branches
`git config --global gitflow.feature.rebase false`

Always rebase feature branches in current Project
`git config gitflow.feature.rebase true`

Always merge feature branches in current Project
`git config gitflow.feature.rebase false`

If you've change the default behaivior to rebase and want to merge back, you can pass the -norebase option.

### CODE REVIEW

**Comment by nvie** [comment]
I think this is more easily tackled with a shell alias.

**Comment by salzig** [comment]
How would you alias "git flow feature finish" to "git flow feature finish --rebase"?

**Comment by nvie** [comment]
You could either do it in Git:

```
git config alias.ff 'flow feature finish --rebase'
```

or in your favourite shell:

```
alias gff='git flow feature finish --rebase'
```

**Comment by salzig** [comment]
sure, nice as shorthand alias, but i prefer the "full" version. btw, with an alias there is no way to define it per project.

**Comment by findchris** [comment]
+1

Not so much for this particular feature, but for more default configurability.  I'd love to be able to have all of my `git flow feature finish` commands use the `-FS` (squash and delete remote branch) options by default without having to remember to pass in flags every time.

Shell aliases work, but you already have a git config scope for gitflow.\* at your disposal, and the implementation is quite simple.  Seems like a no-brainer to me.

**Comment by ckoppelman** [comment]
Also, this allows for the simple integration of third-party tools

**Pull request closed without merging**
