### PR TITLE
Feature/separate gitflow config directory and file

### PR DESCRIPTION
**Pull request by petervanderdoes**
This moves the configuration of gitflow into a separate directory and file. This would be part of a next feature, adding hooks, which also would be stored in the same gitflow directory.

To keep in line with git's structure I used the following naming convention:
- Directory name: .gitflow
- Configuration file: conf

More info can be found in issue #183

### CODE REVIEW

**Comment by pro-logic** [comment]
Also looks like it's related to: https://github.com/nvie/gitflow/issues/147

**Comment by pro-logic** [comment]
Git on windows doesn't seem to like these changes very much... msysGit on a clean repo gives me:

> $ git flow init
> No branches exist yet. Base branches must be created now.
> Branch name for production releases: [master]
> Branch name for "next release" development: [develop]
> error: key does not contain a section: develop
> 
> How to name your supporting branch prefixes?
> Feature branches? [feature/]
> error: key does not contain a section: feature/
> Release branches? [release/]
> error: key does not contain a section: release/
> Hotfix branches? [hotfix/]
> error: key does not contain a section: hotfix/
> Support branches? [support/]
> error: key does not contain a section: support/
> Version tag prefix? []
> error: key does not contain a section:

**Comment by pro-logic** [comment]
Ok, it looks like git-flow-init needs "gitflow_setup_common_variables" to be added line ~39. 

The upgrade process also doesn't get rid of "[gitflow "branch"]" and "[gitflow "prefix"]" sections from .git\conf 

Looks like you also need to run
git config --remove-section gitflow.prefix
git config --remove-section gitflow.branch

**Comment by petervanderdoes** [comment]
pro-logic

Commit 62e21bb takes care of the git flow init problem on a not yet initialized git repo.
Commit a4f6577 takes care of the lingering sections.

Thanks for testing this.

**Comment by pro-logic** [comment]
No problem. When I get a second I'll test the above, but from the code they look fine.

Now let's hope the BDFL likes the patch and accepts it, can't wait to have hooks in my gitflow :)

**Comment by petervanderdoes** [comment]
There is an issue with setting up the configuration outside the .git directory. Any files and/or changes done to the .gitflow directory are not propagated across other branches, which of course if normal git behavior.
This needs to be solved before a proper implementation can be done.

Below is an option

## Separate Branch

We use a gitflow branch. When making changes to the .gitflow configuration or directory or files within .gitflow it needs to be done in the gitflow branch and after making the changes the branch needs to be merged in all existing branches of the repository. 

### git flow commands

New gitflow commands could be introduced:
- git flow config start - Checkout out the gitflow config.
- git flow config finish - This would merge the branch to all existing local branches.
- git flow config publish - Publish the branch remotely

### Naming Convention

To keep in line with naming conventions the branch could be called: gitflow/config
The gitflow/ could be named to whatever you want, just like all other branches.

**Comment by nvie** [comment]
My general feeling about the separate git-flow config directory is that it complicates matters quite a bit (since you're effectively making the configuration part of a _branch_, and git-flow is a tool that helps managing branches). What if you'd initialise a repo for git-flow use and then change any of the values on another branch? git-flow will get confused and your repo will easily be messed up. (I see you made the same observation already.)

To overcome this we need to introduce a few more subcommands to deal with the potential conflicting configuration or distribution of the configuration changes over branches (complex), or simply don't do it at all (simple). When stuff gets more complicated, I'd like to take a step back and remember the problem we're solving here and what tools we're trying to solve it with.

I remember having the same design discussion in my head when I started writing git-flow almost 2 years ago. I remember deliberately choosing the simple variant over the more complex one, accepting the fact that, yes, you need to run git-flow init in each repo and, yes, enter the same values in all repos in order for it to work correctly.

But here's the thing: when you're not using git-flow at all, you always have conventions your project team uses to work together. This relates to branch names, coding conventions, build settings, anything. git-flow is just a tool that helps you focus around a "standardised" way of working together.

I sincerely believe that git-flow is the wrong tool for solving your problem, even though many (including myself) encounter the same problem every so often.

If you want to have it automated in order to avoid human mistakes in your team, why not simply include a script in your repository that sets the config variables manually? E.g. does the equivalent of:

```
git config gitflow.branch.master 'master'
git config gitflow.branch.develop 'develop'
git config gitflow.prefix.feature 'feature/'
git config gitflow.prefix.release 'release/'
git config gitflow.prefix.hotfix 'hotfix/'
git config gitflow.prefix.support 'support/'
git config gitflow.prefix.versiontag ''
```

Since that is all that `init` really does.

**Comment by petervanderdoes** [comment]
Alright then. Closing the pull request

**Pull request closed without merging**
